/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Odev;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import org.checkerframework.checker.units.qual.A;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test
    public void testFound(){
        int a = 5;
    
    }
    @Test
    public void testNotFound(){
        int a = 7;
    
    }
}
